### ISSUE TITLE
Deterministic Sampler tests are flaky

### ISSUE THREAD

**Issue by tredman** [honeycombio/honeytail#122]
Could be an actual problem with the sampler:

```
--- FAIL: TestDeterministicSampler (3.17s)
    deterministic_sampler_test.go:85: Sampled more or less than we should have:  1895 (sample rate  100 )
```

**Comment by nathanleclaire** [comment]
Heh... so close. 1900 is the cutoff -

200,000 events / 100 sample rate => 2000 sampled events * 0.95 margin of error => 1900

**Comment by vreynolds** [comment]
Not seeing recent failures, but we've seen this in other projects: https://github.com/honeycombio/beeline-go/pull/289
