### ISSUE TITLE
install fails with unexpected module path for logrus

### ISSUE THREAD

**Issue by Jim-Lambert-Bose** [honeycombio/honeytail#128]
running: go get github.com/honeycombio/honeytail

Fails with this error: go: github.com/Sirupsen/logrus@v1.3.0: parsing go.mod: unexpected module path "github.com/sirupsen/logrus"

I did successfully install it by:
export GO111MODULE=off
go get github.com/honeycombio/honeytail

**Comment by maplebed** [comment]
Thanks for the report.  What version of Go do you have installed? I'm going to guess it's a combination of go 1.11 and the Sirupsen/sirupsen import path issue.

**Comment by Jim-Lambert-Bose** [comment]
go version go1.11.5 darwin/amd64

**Comment by JamieDanielson** [comment]
Closing as this does not appear to be an issue anymore. Feel free to request a re-open if it's still relevant.
