### ISSUE TITLE
[docs] Download instructions for non-linux OS

### ISSUE THREAD

**Issue by jmorrell** [honeycombio/honeytail#130]
👋 I'm trying to try out Honeycomb and backfill an example data set. My thought process:

- Oh cool, they have a backfill doc, and a cli tool that can help!
- I just need to download honeytail... Let's look at the [doc](https://docs.honeycomb.io/getting-data-in/honeytail/)

![Running the Honeytail agent | Honeycomb 2019-03-14 18-06-22](https://user-images.githubusercontent.com/175496/54401689-dfbfe280-4685-11e9-8135-e7a6851d6e9a.png)

Oh... I use a mac tho...

*finds github repo*

Okay, I can [use `go get`](https://github.com/honeycombio/honeytail#installation)

```
go get github.com/honeycombio/honeytail
```

That works for me, but I just started using golang not too long ago, and wouldn't have had that toolchain installed a month ago. A `brew` option, a self-contained installer, or even just the `go get` instructions in the official docs would have been really helpful here.

**Comment by nelz9999** [comment]
I noticed that too...

I'd suggest a tool like https://goreleaser.com/ that can help publish a wider variety of executables. (I haven't used that yet myself, but it seems like it'd be helpful here.)

**Comment by JamieDanielson** [comment]
The public docs have been updated since the issue was reported to include a variety of install options, including cloning from source. We'll close this out but feel free to request a re-open if it's still relevant.
