### ISSUE TITLE
Syslog parser rfc3164 format not reading

### ISSUE THREAD

**Issue by budgester** [honeycombio/honeytail#142]
Trying to read my application syslog generated logfiles, on an ubuntu machine.

`root@ip-10-100-10-36:/var/log# cat test.log 
<34>Jan 16 11:23:35 ip-10-100-10-36 ia-upload-service[16312]: 2020-01-16 11:23:35,173 - root - INFO - Looking for new tasks
Jan 16 11:23:35 ip-10-100-10-36 ia-upload-service[16312]: 2020-01-16 11:23:35,173 - root - INFO - Looking for new tasks`

using 

`honeytail --parser=syslog --writekey=****** --file=/var/log/test.log --dataset='TestI' --syslog.mode=rfc3164 --backfill --debug`

gives the output

`INFO[0000] Starting honeytail                           
DEBU[0000] about to call tail.TailFile                   conf={Paths:[/var/log/test.log] FilterPaths:[] Type:0 Options:{ReadFrom:beginning Stop:true Poll:false StateFile:}} location=<nil> statefile=/tmp/test.leash.state tailConf={Location:<nil> ReOpen:false MustExist:true Poll:false Pipe:false RateLimiter:<nil> Follow:false MaxLineSize:0 Logger:0xc4200aeb40}
DEBU[0000] attempting to process line                    line=<34>Jan 16 11:23:35 ip-10-100-10-36 ia-upload-service[16312]: 2020-01-16 11:23:35,173 - root - INFO - Looking for new tasks
DEBU[0000] attempting to process line                    line=Jan 16 11:23:35 ip-10-100-10-36 ia-upload-service[16312]: 2020-01-16 11:23:35,173 - root - INFO - Looking for new tasks
DEBU[0000] Initializing stats reporting. Will print stats once/60 seconds 
DEBU[0000] lines channel is closed, ending syslog processor 
DEBU[0000] event send record received                    body= duration=48.721427ms error=<nil> retry_send=false status_code=202 timestamp=2020-01-16 11:23:35 +0000 UTC
INFO[0000] Summary of sent events                        avg_duration=48.721427ms count=1 count_per_status=map[202:1] errors=map[] fastest=48.721427ms lifetime_count=1 response_bodies=map[:1] slowest=48.721427ms
INFO[0000] Last parsed event                             event=map[facility:4 severity:2 process:ia-upload-service timestamp:2020-01-16 11:23:35 +0000 UTC hostname:ip-10-100-10-36 content:2020-01-16 11:23:35,173 - root - INFO - Looking for new tasks priority:34] event_timestamp=2020-01-16 11:23:35 +0000 UTC
INFO[0000] Total number of events sent                   number sent by response status code=map[202:1] total attempted sends=1
INFO[0000] Honeytail is all done, goodbye! `

My understanding is the standard rfc3164 format does not have the <34> 'priority' field  at the start, and this is reason that honeytail doesn't parse my log files.

And looking at https://rsyslog-5-8-6-doc.neocities.org/rsyslog_conf_templates.html it appears that the format honeycomb has marked as rfc3164 could be the ForwardFormat.

**Comment by JamieDanielson** [comment]
Hello,

As we enter 2022 Q1, we are trimming our OSS backlog. We will be closing this issue as it is a low priority for us to fix. It is unlikely that we'll ever get to it, and so we'd like to set expectations accordingly.

If this issue is important to you, please feel free to ping here and we can discuss/re-open.
