### ISSUE TITLE
Issue with Honeytail not parsing through Arangodb logs

### ISSUE THREAD

**Issue by hkhazi** [honeycombio/honeytail#189]
Hi, had some some issues with parsing through some arangodb logs.
When running with --debug, I get `DEBU[0000] logline didn't parse, skipping.` throughout the whole log file. 
The command I'm using:
`./honeytail --writekey=writekey --dataset='example-arango' --parser=arangodb --file=arangod.log --backfill --debug`

I attached an example of the log I am running. 
[arangod.log](https://github.com/honeycombio/honeytail/files/6259027/arangod.log)

**Comment by vreynolds** [comment]
Thank you for letting us know! We’ll investigate as soon as we can. 🕵🏽‍♀️

**Comment by kentquirk** [comment]
@hkhazi just from a quick look at the code, the Arangodb driver for honeytail is only expecting to ingest `{requests}` entries from the logs. All other log messages are discarded. The log you posted has no requests entries at all.

Even with that, however, your logs include two bracketed fields: `[31923] INFO [a220f]` for example. The first is the PID, but I don't see what the second is, nor do I see it in the arango documentation. 

Two questions for you, please:
* what do you expect to capture for these additional log messages?
* what is that second bracketed field?

**Comment by JamieDanielson** [comment]
Hello,

As we enter 2022 Q1, we are trimming our OSS backlog. We will be closing this issue as it is a low priority for us to fix. It is unlikely that we'll ever get to it, and so we'd like to set expectations accordingly.

If this issue is important to you, please feel free to ping here and we can discuss/re-open.
