### ISSUE TITLE
Honeytail 1.4.1 only supports a single value for AddFields in .conf

### ISSUE THREAD

**Issue by porterctrlz** [honeycombio/honeytail#197]
I haven't had a chance to repro this from source or bisect, but in upgrading from an ancient version of Honeytail to `1.4.1`, I noticed that the extra fields I'd been adding per-honeytail instance via `AddFields key=val` in the config were getting dropped.

Previously I was invoking Honeytail something like this:
`/usr/bin/honeytail -c /etc/honeytail/honeytail_nginx.conf`

But as a work-around I'm now doing this:
`/usr/bin/honeytail -c /etc/honeytail/honeytail_nginx.conf --add_field parser=nginx --add_field hostname=api-0.env.hostname.com --add_field service=api` etc.

This is mostly 6-of-1, half-dozen of another, but since AddFields still shows up in the default config, I was wondering if there was a regression (or if I'm simply not specifying it correctly).

Old configs looked like:
```AddFields = parser=nginx
AddFields = parser=nginx
AddFields = hostname=api-0.env.hostname.com
AddFields = service=api
```

Thanks!

**Comment by sarahhodne** [comment]
We're seeing something similar too, with a config like this:

```ini
AddFields = "replica_set_name=foo"
AddFields = "host=foo-1"
```

Oddly, the `replica_set_name` field seems to be included, but the `host` field is only reported by some of our hosts. I've double-checked the configuration and with the exception of the exact hostname the configuration and honeytail version is otherwise identical between the different servers.

**Comment by sarahhodne** [comment]
[From Slack](https://honeycombpollinators.slack.com/archives/C4T3A32CX/p1623243659275900?thread_ts=1623235755.272700&cid=C4T3A32CX), it seems to be an issue with the upgraded version of go-flags in 1.4.0 vs 1.3.0, potentially this commit: https://github.com/jessevdk/go-flags/commit/1878de27329cba29066dc088d84b3ce743885f82.

**Comment by JamieDanielson** [comment]
Hi @porterctrlz , sorry for the delay on this! There is a new [example](https://github.com/honeycombio/honeytail/blob/main/example/honeytail-example.conf) added that uses the latest version [v1.6.0](https://github.com/honeycombio/honeytail/releases/tag/v1.6.0), and AddFields is working in the config file. I added it like this: `AddFields = "backfilled_log=yes"`. 

It definitely seems possible that a dependency change along the way fixed this up, but it should be good to go now.

I'll close this for now but if this continues to be an issue feel free to add a comment with more details and we can reopen.

**Comment by chomey** [comment]
This doesn't appear to be working for me on version Honeytail version v1.6.

**Comment by MikeGoldsmith** [comment]
Hi @chomey - please can you provide more details on what you're seeing / expect to happen?

**Comment by chomey** [comment]
https://github.com/honeycombio/honeytail/issues/197 https://github.com/honeycombio/honeytail/issues/261

**Comment by jerm** [comment]
I just upgraded from 1.3.0 to 1.6.2 and still only the first AddFields entry in the config file works. 

What i expect to happen is that they all work, or if that's no longer possible, for the workaround that @chomey mentioned to be implemented. 

In the meantime I'm going to try to use the --add_field commandline workaround with our tooling, but if that's not workable, I'm still stuck on 1.3.0

**Comment by jerm** [comment]
At the very least the "May be specified multiple times" should be removed from the docs. https://github.com/honeycombio/honeytail/blob/main/main.go

**Comment by kentquirk** [comment]
Reopening while I work on #261.
