### ISSUE TITLE
Mention config file as an option in the docs

### ISSUE THREAD

**Issue by vreynolds** [honeycombio/honeytail#220]
Follow-up from #219 

Add a note about the config file in the readme and the [public docs](https://docs.honeycomb.io/getting-data-in/integrations/databases/postgresql/logs/#install-and-run-honeytail)

**Comment by bdarfler** [comment]
It looks like this is documented in a different section of our docs

https://docs.honeycomb.io/getting-data-in/integrations/honeytail/#versioning-honeytail-config
