### ISSUE TITLE
GetTimestamp says it deletes the time value it returns, but not if it's already a time.Time

### ISSUE THREAD

**Issue by kentquirk** [honeycombio/honeytail#238]
Documentation for GetTimestamp() says that it deletes the timestamp that it finds from the map that's passed in.

However, if this timestamp is already in time.Time format, it (simply returns)[https://github.com/honeycombio/honeytail/blob/0ff79e56031cc7281606b51e781da4e956a5abe7/httime/httime.go#L108].

There should be a delete before this return.

This was found by code inspection.

**Comment by robbkidd** [comment]
[This seems intentional](https://github.com/honeycombio/honeytail/commit/7338285b409768bdf366f8e277769f1523880ae1), though agreed it is inconsistent with the function documentation. Is the return-of-a-Time-without-deleting-it-from-map causing a problem?
