### ISSUE TITLE
Ability to perform health checks on honeytail container

### ISSUE THREAD

**Issue by shayonj** [honeycombio/honeytail#271]
**Is your feature request related to a problem? Please describe.**

When running honeytail in containerized workloads, it'd be nice to perform some of sort of health check to indicate that the process/container is "up and doing fine". For instance when running on kubernetes, fargate, etc. 

**Describe the solution you'd like**

- Exposing an endpoint like `/health` that returns a `200` could be nice. Users can then do a `curl..`
- Or if http server / endpoint is not an option, we can also do something  like `honeytail health` (to introduce a new command) which returns some output with an exit code of `0`, or `1` accordingly on the success of the validation command. Behind the scenes it could make some sort of auth/validation request against Honeycomb endpoint to ensure the setup is right (maybe use the API key to perform a auth ping check?). Or if there is a way to determine that internally without having to thrash honeycomb API, then thats grand too.

**Describe alternatives you've considered**

Running `pgrep -x 'honeytail'` 

**Additional context**

I am happy to work propose a PR if there is interest and if the high level idea here sounds like a something that worth building into honeytail :)

**Comment by kentquirk** [comment]
Hi, @shayonj -- thanks for the issue.

"Up" is pretty easy to determine, and it would be fairly straightforward to add an (optional) endpoint that would listen on a specified port and return 200 (or simply not respond). The question is whether it's worth it.

Honeytail already verifies that the key is good before starting and will fail immediately in that case.

Beyond that, there's nothing much I've thought of that an operating honeytail could do to assert that it's "doing fine". Basically, if the task is alive (which presumably the container can tell) it's OK.

Do you think that a /health endpoint that never returns anything other than 200 is useful? If so, what problem does it solve?
