### ISSUE TITLE
Honeytail doesn't skip syslog prefix when parsing

### ISSUE THREAD

**Issue by pbrisbin** [honeycombio/honeytail#31]
We push all logs to a shared `/var/log/messages` via syslog. This means all log lines have some additional prefixing:

```
Nov 17 14:29:29 cc-prod-tokumx-blue mongod.27018: Thu Nov 17 19:29:29.136 [conn596789] query code_climate_production.constants ...
^ prefix                                        : ^ parsable mongo log starts
```

I'm able to work around this by first piping the log through:

```
cut -d : -F 4- | sed 's/^ //'
```

Then honeytail processes things successfully.

Note: `mloginfo` accepts our logs without pre-stripping that prefix.

**Comment by maplebed** [comment]
@pbrisbin will the flag proposed in https://github.com/honeycombio/honeytail/pull/30 work for you?

**Comment by pbrisbin** [comment]
Doh, I totally missed that. I checked existing Issues, not PRs. That would definitely work.

**Comment by pbrisbin** [comment]
Just tried out the new flag and it worked great. Thanks for the quick turnaround.
