### ISSUE TITLE
allow disabling logs

### ISSUE THREAD

**Issue by verygoodsoftwarenotvirus** [honeycombio/honeytail#330]
**Is your feature request related to a problem? Please describe.**
We use honeytail to forward logs to honeycomb from our ECS containers. In the ECS logs (which I have to look at sometimes as not all logs are forwarded), we keep seeing a ton of log lines caused by [this line.](https://github.com/honeycombio/honeytail/blob/f5861dc5d9cdc3a83e24f7b67140fd04523a08f4/response_stats.go#L85-L94) These logs pollute the log stream and make it harder to find other relevant logs outside of the Honeycomb interface.

**Describe the solution you'd like**
I'd love to be able to set an env var (i.e. `HONEYTAIL_NO_LOG`) that would prevent these logs from being written at all.

**Describe alternatives you've considered**
I've contemplated not using honeytail at all for logs, but migration away from the status quo is just not something we have capacity for at the moment.

**Additional context**
n/a

**Comment by MikeGoldsmith** [comment]
Hey @verygoodsoftwarenotvirus  - thanks for raisng the issue and sorry for the delay in responding.

I've put together #332 to help with the problem you're facing. With it, you can set the desired log level to omit the log entries you're not interested in.
