### ISSUE TITLE
honeytail will fail if gonx regex fields are missing completely

### ISSUE THREAD

**Issue by nathanleclaire** [honeycombio/honeytail#95]
I ran into a somewhat odd case with `gonx` - 

if you have the log format set like recommended at https://honeycomb.io/docs/connect/nginx#missing-default-options:

```
log_format combined '$remote_addr - $remote_user [$time_local] $host '
    '"$request" $status $bytes_sent $body_bytes_sent $request_time '
    '"$http_referer" "$http_user_agent" $request_length "$http_authorization" '
    '"$http_x_forwarded_proto" "$http_x_forwarded_for" $server_name';
```

But don't have `server_name` set, it seems the nginx log line will leave it off the end completely?

e.g.:

```
172.22.0.1 - [16/Feb/2018:22:43:44 +0000] localhost "POST /api/todos/ HTTP/1.1" 200 291 136 0.053 "-" "curl/7.54.0" 228 "-" "-" "-"
```

This causes the regex parsing to fail completely (thus sending no events at all) when it should ideally be giving best effort. the generated regexp:

```
^(?P<remote_addr>[^ ]*) - \[(?P<time_local>[^]]*)\] (?P<host>[^ ]*) "(?P<request>[^"]*)" (?P<status>[^ ]*) (?P<bytes_sent>[^ ]*) (?P<body_bytes_sent>[^ ]*) (?P<request_time>[^ ]*) "(?P<http_referer>[^"]*)" "(?P<http_user_agent>[^"]*)" (?P<request_length>[^ ]*) "(?P<http_authorization>[^"]*)" "(?P<http_x_forwarded_proto>[^"]*)" "(?P<http_x_forwarded_for>[^"]*)" (?P<server_name>[^ ]*)$
```

Not urgent since it was somewhat PEBKAC (didn't set `server_name`), but ideally... we should either account for this in the regex, or alert the user that some critical field missing is the reason for the failure.

**Comment by pravipati** [comment]
> we should either account for this in the regex, or alert the user that some critical field missing is the reason for the failure.

I don't mean to hijack your thought, but I did want to echo this notion for https://github.com/honeycombio/honeytail/blob/master/parsers/nginx/nginx.go#L104

the line parser used ☝️ silently fails which is *especially* tricky when the user didn't notice that the files being fed in were gzipped and not already text logs 😅. I think it'd be 🤘 to add the type of alerting you're talking about.

**Comment by nathanleclaire** [comment]
i think this should be fixed with the gonx regex modification now
